name: Build and Push UniHub-sistemiWeb to GHCR

on:
  push:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup di Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login a GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Imposta un tag "pulito" sostituendo / con -
      - name: Prepare Docker tag
        id: vars
        run: |
          SAFE_TAG=${GITHUB_REF_NAME//\//-}
          echo "safe_tag=$SAFE_TAG" >> $GITHUB_OUTPUT

      # 5️⃣ Build e push dell'immagine
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/frankyeee0/unihub-sistemiweb:latest
            ghcr.io/frankyeee0/unihub-sistemiweb:${{ steps.vars.outputs.safe_tag }}
